apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: product-service-secret
  namespace: cloudmart
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: product-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudmart/product-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-service-secret
  namespace: cloudmart
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: order-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudmart/order-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: cloudmart
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: cloudmart/ghcr-pull
        property: username
    - secretKey: password
      remoteRef:
        key: cloudmart/ghcr-pull
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend-oauth-secret
  namespace: cloudmart
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: frontend-oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: cloudmart/google-oauth
        property: client-id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: cloudmart/google-oauth
        property: client-secret
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: cloudmart/google-oauth
        property: nextauth-secret
