apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pull in all 4 base service manifests
namespace: cloudmart

resources:
  - namespace.yaml
  - ../../base/product-service
  - ../../base/order-service
  - ../../base/api-gateway
  - ../../base/frontend

labels:
  - pairs:
      environment: local
    includeSelectors: false

# Override images to pull from GHCR
images:
  - name: cloudmart/product-service
    newName: ghcr.io/nidhi-s12/cloudmart/product-service
    newTag: latest
  - name: cloudmart/order-service
    newName: ghcr.io/nidhi-s12/cloudmart/order-service
    newTag: latest
  - name: cloudmart/api-gateway
    newName: ghcr.io/nidhi-s12/cloudmart/api-gateway
    newTag: latest
  - name: cloudmart/frontend
    newName: ghcr.io/nidhi-s12/cloudmart/frontend
    newTag: latest

# Apply environment-specific patches from the patches/ folder
patches:
  - path: patches/frontend-nodeport.yaml
  - path: patches/api-gateway-nodeport.yaml
  - path: patches/frontend-env.yaml
