apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudmart

resources:
- namespace.yaml
- ../../base/product-service
- ../../base/order-service
- ../../base/api-gateway
- ../../base/frontend
- ../../base/ingress
- ../../base/kafka
- ../../base/external-secrets

labels:
- pairs:
    environment: production

# Pull from GHCR — same as local but will use sha tags once CI is updated
images:
- name: cloudmart/api-gateway
  newName: ghcr.io/nidhi-s12/cloudmart/api-gateway
  newTag: sha-0065f0d
- name: cloudmart/frontend
  newName: ghcr.io/nidhi-s12/cloudmart/frontend
  newTag: sha-0c924df
- name: cloudmart/order-service
  newName: ghcr.io/nidhi-s12/cloudmart/order-service
  newTag: sha-0065f0d
- name: cloudmart/product-service
  newName: ghcr.io/nidhi-s12/cloudmart/product-service
  newTag: sha-005c6cb

patches:
- path: patches/frontend-env.yaml
- path: patches/product-service-env.yaml
